name: Outputs Demo Workflow

on:
  - push

jobs:
  info:
    runs-on: ubuntu-latest
    outputs:
      commit-sha: ${{ steps.commit.outputs.sha }}
      commit-message: ${{ steps.message.outputs.message }}
      branch-name: ${{ steps.branch.outputs.name }}
    steps:
      - uses: actions/checkout@v5

      - name: Get commit SHA
        id: commit
        run: |
          SHA=$(git rev-parse --short HEAD)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Get commit message
        id: message
        run: |
          MESSAGE=$(git log -1 --pretty=%B)
          echo "message=$MESSAGE" >> $GITHUB_OUTPUT

      - name: Get branch name
        id: branch
        run: |
          NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "name=$NAME" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: info
    steps: 
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Print commit info
        run: echo "Building commit ${{ needs.info.outputs.commit-sha }} on branch ${{ needs.info.outputs.branch-name }}"

  summary:
    runs-on: ubuntu-latest
    needs: [info, build]
    steps:
      - name: Print commit information
        run: |
          echo "Commit SHA: ${{ needs.info.outputs.commit-sha }}"
          echo "Commit Message: ${{ needs.info.outputs.commit-message }}"
          echo "Branch Name: ${{ needs.info.outputs.branch-name }}"



